#
# Copyright (c) 2021-2025 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Pull Request Check

# Trigger the workflow on pull request
on: [pull_request]

jobs:
  check-artifacts:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout che-code source code
        uses: actions/checkout@v4
      - name: Generate artifacts
        run: ./build/artifacts/generate.sh
      - name: Check if artifacts are up to date
        run: |
          if [[ $(git diff --name-only | wc -l) != 0 ]]; then
            # Print difference
            git --no-pager diff
          
            echo "[ERROR] Artifacts is not up to date."
            echo "[ERROR] Run './build/artifacts/generate.sh' and include file into the commit."
            exit 1
          fi
